version: '3.9'

services:
  db:
    image: ankane/pgvector
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
    ports:
      - "15432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  postgres-mcp:
    image: crystaldba/postgres-mcp
    container_name: postgres-mcp

    # Variables d'environnement
    environment:
      DATABASE_URI: postgresql://postgres:example@localhost:15432/postgres

    # Ports exposés
    ports:
      - "8000:8000"

    # Commande à exécuter dans le conteneur
    command: ["--access-mode=unrestricted", "--transport=sse"]

    restart: unless-stopped
